steps:
  # Example build steps
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_REPO_NAME}:${_BRANCH_NAME}', '.']
    
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_REPO_NAME}:${_BRANCH_NAME}']

substitutions:
  _REPO_NAME: ''  # Will be provided by the workflow
  _BRANCH_NAME: '' # Will be provided by the workflow

options:
  logging: CLOUD_LOGGING_ONLY
